### ISSUE TITLE
[non programmer question] asking for am installation guide on a web server.

### ISSUE THREAD

**Issue by SpannerWZ** [derpibooru/philomena#160]
hello, a friend asked me to build a website and we are searching for some booru/image board solutions that we can use in our site, at this moment we are testing with shimmie, seeing that is easy to use and install, the issue iis that is not that feature filled as Philomena, so i'm asking here having 0 programing skills.

can i install this software on a remote server (host) and build a website with it?, i tried installing it before but nothing worked, at this time i'm just using shimmie and modifying their PHP and CSS files to adapt to our needs and to improve the user experience (my friend is an avid user of derpibooru), but as you can imagine im not well informed on PHP language and we really would love to have derpibooru features

**Comment by liamwhite** [comment]
Philomena is rather complicated to set up at the time being. In the future I hope to provide Kubernetes files to allow automatic deployment of the software to a suitable cloud host, but right now the only way to use the software is to install it yourself on a dedicated server. Follow the setup as described in the Dockerfile, or as previously done in the [Vagrant files](https://github.com/derpibooru/philomena/tree/9ca134b9a92c41ad0276e452f8502b876aaa2d4e/vagrant).

The application will not run on shared hosting due to its hard requirement for PostgreSQL and Elasticsearch.
