### ISSUE TITLE
Site can handle only 1 notification about new thread in subforum

### ISSUE THREAD

**Issue by stsyn** [derpibooru/philomena#191]
Title says everything. Only fist (or latest) notification is shown. Also related to #39

**Comment by parasprite** [comment]
This is probably related, but it's something I've been noticing a lot recently.

1. Subscribe to 2 threads in same subforum
2. Trigger a notification on both threads
3. Notifications show for thread A and thread B
4. Visit thread A
5. Both thread A and thread B disappear from notifications

Expected behavior: Thread B remains in notifications.
