### ISSUE TITLE
Tag slugs being double-encoded in URLs

### ISSUE THREAD

**Issue by Sibusten** [derpibooru/philomena#203]
**Describe the bug**
Tag slugs are being double-encoded in URLs. For example:
`twilight sparkle (alicorn)` -> `twilight+sparkle+%28alicorn%29` -> `twilight%2Bsparkle%2B%2528alicorn%2529`

**To Reproduce**
1. Go to the `twilight sparkle (alicorn)` tag page
2. Observe the URL is `https://derpibooru.org/tags/twilight%2Bsparkle%2B%2528alicorn%2529`

**Expected behavior**
Tag slugs should only be encoded once. The URL for `twilight sparkle (alicorn)` should be `https://derpibooru.org/tags/twilight+sparkle+%28alicorn%29`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 80.0

**Comment by liamwhite** [comment]
Fixed upstream.
1. API clients should URI encode the tag slug if they wish to generate links to tag endpoints (but note it is easier to use the search endpoint as a stable link to a tag results path)
2. Site operators will need to rebuild slugs after deploying this commit if they wish to take advantage of the fix for existing tags

**Comment by Sibusten** [comment]
This issue appears to still be happening (at least on Derpibooru). It's different than before.

The tag slug URL is now `twilight+sparkle+%2528alicorn%2529`. Spaces are not being double-encoded, but other special characters are. In this case: `(` -> `%28` -> `%2528`

**Comment by liamwhite** [comment]
Whatever appears there is the result of stored encoded data. The site operator will have to rebuild the slugs manually to get rid of the double encoding.
