### ISSUE TITLE
Production deployment (Docker mounts/volumes, HTTP API)

### ISSUE THREAD

**Issue by imtbl** [derpibooru/philomena#32]
Hello,

first of all, thank you for making Philomena FOSS. From my experience while checking it out on Derpibooru it's easily one of the best booru softwares.

I've considered setting up an instance for private usage but ran into some questions that hopefully won't cause much trouble to answer. Apologies if this is already documented somewhere -- I couldn't find it.

1. I see the code is currently bind-mounted via `.:/srv/philomena`. For production, you'd ideally only mount the data directories that need to be persisted (either via bind mount or volume) and use `COPY` during the image build to get the code into the container. Can you tell me which directories would be required to to be mounted instead of just copied? Based on that information I could create my own production Docker image.
2. Before I start digging through the code, is there any documentation about the HTTP API? I'm not talking about the (well-documented) [ read-only API](https://derpibooru.org/pages/api). I was instead assuming there would also be routes to upload media, add tags etc. See [here](https://github.com/rr-/szurubooru/blob/master/doc/API.md) for an example of API docs of another booru software. This would be particularly interesting to me as I'd be looking into writing some sort of bridge software to copy data to/from [hydrus](https://hydrusnetwork.github.io/hydrus/).
3. Is there a particular reason the images are not available on Docker Hub? Are you perhaps using your own registry? This is not an issue for me though. I'm more curious, since setting up autobuilds on Docker Hub (or building via GitHub Actions and pushing to Docker Hub) is quite straight forward from my experience.

**Comment by liamwhite** [comment]
1. The Dockerfile is configured for development, in which it is desirable to see changes appear immediately after making them. You will want to mount the generated Mnesia cache directory, which requires you to set a real hostname for the container, and `public/system`, otherwise you will have no session persistence and the nginx container won't be able to read image files (they'll also get deleted every time the container is reset). I need some assistance with the final part, which is Elasticsearch persistence. I realized yesterday from https://github.com/derpibooru/philomena/issues/31#issuecomment-583244882 that I do not have the correct directory in the named volume for Elasticsearch to persist. It needs to be set to `/usr/share/elasticsearch/data`, however Elasticsearch raises EACCES and dies when I try to set it to this.
2. There is currently no writeable API. As of now, in order to write to the application you must use the HTML format endpoints; those are enumerated in the [router](https://github.com/derpibooru/philomena/blob/master/lib/philomena_web/router.ex). We are planning to add a writeable API.
3. There are currently no production images, because we aren't running Philomena in production with Docker.

**Comment by imtbl** [comment]
Thanks for the quick response, that answers my questions. If anything further comes up, I'll join the Discord as suggested. :)
