### ISSUE TITLE
Mod Tool - Tag reversal tool does not work

### ISSUE THREAD

**Issue by TheSmilingPony** [derpibooru/philomena#44]
**Describe the bug**
Tag reversal mod tool leads to a 404 error.

**To Reproduce**
1. Go to a tag changes page
2. Click on select some tag checkboxes
3. Hit Reverse
4. Page loads for some time and results in a 404

**Expected behavior**
Tags are reversed and no error is given

**Comment by liamwhite** [comment]
I just tried it and it works. Are there specific steps that need to be taken?

**Comment by stsyn** [comment]
Tried it few days ago with >>2335123 (before deletion) - didn't worked, had to copypaste manually.

**Comment by liamwhite** [comment]
I have no real insight into why this is failing. Presumably it is running into some sort of write conflict and failing.

I have tried removing the associated transaction. This makes the operation no longer atomic, which could potentially lead to consistency errors, but maybe that doesn't matter so much if it's unusable otherwise.

**Comment by liamwhite** [comment]
Should have been fixed by philomena-dev/philomena@b97073ee1892099c57b8720ed909cd348c5daf43
